### ISSUE TITLE
Injest data from JSON

### ISSUE THREAD

**Issue by robinlennox** [controlscanmdr/cyphondock#34]
Hi Team,

I'm wanting to import an a JSON file on regular intervals into Cyphon for Intel... Such as https://www.reddit.com/r/netsec/.json

However, I'm hitting a brick wall.... can you point me in the right direction?

**Comment by lhadjchikh** [comment]
This sounds similar to https://github.com/dunbarcyber/cyphondock/issues/5, but we haven't implemented a solution yet. We have a general framework we can use for interacting with APIs, but I will probably need to create a new package to handle this kind of query. I'll see what I can do!

**Comment by robinlennox** [comment]
Agreed this is similar to #5, however as that relates to API's I think this should be pulled out otherwise #5 could become overly complicated as this is to do with JSON.

I'm using the following as the JSON sample: https://www.reddit.com/r/netsec/.json

**Comment by lhadjchikh** [comment]
If it's just a matter of ingesting JSON from a file, I think you could just use Filebeat and the [Logstash JSON filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html) to send the JSON data to RabbitMQ, where it could be processed by Cyphon's watchdogs. If you also need something to periodically query a URL, fetch the JSON, avoid duplicates, etc., that will require a solution like in https://github.com/dunbarcyber/cyphondock/issues/5.

**Comment by robinlennox** [comment]
I was thinking about pulling the JSON and passing it straight to logstash via a TCP input plugin(https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html). I think spinning up another filebeat may be overkill.

**Comment by fatalglitch** [comment]
Something like this can be handled through Logstash with the http_poller input plugin:
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http_poller.html
