### ISSUE TITLE
Injest data from an API

### ISSUE THREAD

**Issue by trevan** [controlscanmdr/cyphondock#5]
I have an API that I can get a list of alerts from it and I'd like to feed it into cyphon.  I'm reading the docs and I'm kind of confused on what are all the parts I have to do.

According to http://cyphon.readthedocs.io/en/latest/user-manual/data-collection.html, it sounds like I either feed them in through logstash or I feed them through rabbitmq.  Do I have to do both of them, or just one?

After that, it sounds like I have to setup a bunch of data processing items (http://cyphon.readthedocs.io/en/latest/user-manual/data-processing.html).  Is there a way to easily bypass that for JSON data from an API?

**Comment by lhadjchikh** [comment]
If it were logs, you would use the RabbitMQ output plugin for Logstash to send it from Logstash to RabbitMQ to Cyphon. You can see an example [here](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf#L41-L52).

However, if you're talking about JSON data from an API, we would need to integrate it using the framework in the [Ambassador package](http://cyphon.readthedocs.io/en/latest/architecture/collecting-data.html#external-apis). For example, the Aggregator package (which is based on the Ambassador package) focuses on APIs that accept queries based on keywords, locations, and usernames. A more general-purpose package for REST API requests is on our roadmap, but isn't yet in being, unfortunately. We hope to get contributors to help us with this. :-)

If you can provide more details on the API, I can look into it more to see how we might integrate it with Cyphon.

**Comment by fatalglitch** [comment]
Something like this can be handled with Logstash via the http_poller input plugin
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http_poller.html
