### ISSUE TITLE
watchdogs_1 | ERROR An error occurred while processing the message

### ISSUE THREAD

**Issue by santi10** [controlscanmdr/cyphondock#76]
Hi,

I'm rearching because Cyphon doen't show the events on dashboard. I've seen this message on "watchdogs_1"

watchdogs_1      | ERROR An error occurred while processing the message '{"TimestampAlert":"04/18/2018 12:50:20","syslog_facility_code":1,"EventID":"2264456509","message":": My fields match events"}':
watchdogs_1      |   get_by_collection_nk() argument after * must be an iterable, not NoneType
watchdogs_1      | Traceback (most recent call last):
watchdogs_1      |   File "receiver/receiver.py", line 119, in process_msg
watchdogs_1      |     consumer_func(doc_obj)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/transaction.py", line 97, in _decorator
watchdogs_1      |     result = func(*args, **kwargs)
watchdogs_1      |   File "/usr/src/app/cyphon/alarms/models.py", line 70, in process
watchdogs_1      |     alarms = self.find_relevant(doc_obj.distillery)
watchdogs_1      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
watchdogs_1      |     res = instance.__dict__[self.name] = self.func(instance)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/documents.py", line 108, in distillery
watchdogs_1      |     return distillery_model.objects.get_by_collection_nk(*natural_key)
watchdogs_1      | **TypeError: get_by_collection_nk() argument after * must be an iterable, not NoneType**

I think that this message is my issue...do you know the "why" of this problem???? What i can do what I can see the alerts on Cyphon???

Please, help me about this

Regards

**Comment by fatalglitch** [comment]
You are missing a collection field in your alert data. Please review the tutorial about Logstash, specifically the Filters sections
http://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html#filters

**Comment by santi10** [comment]
Hi fatalglitch,

This is my config on logstash:

filter {
  if [type] == "alert" {
    grok {
      match => { "message" => "Alarm\x3a(?<Client>(.*))\x7c(?<Severity>(.*))\|(?<
Message>([^\n\r]+)),Assignee\x3a(?<Assignee>(.*)),TriggerDate\x3a(?<TimestampAler
t>(.*)),Summary\x3a(?<Summary>(.*)),DeviceName\x3a(?<DeviceName>(.*)),Host\x3a(?<
Host>(.*)),EventID\x3a(?<EventID>(.*)),EventSubtype\x3a(?<EventSubtype>(.*)),Even
tcount\x3a(?<Eventcount>(.*)),AverageSeverity\x3a(?<AverageSeverity>(.*)),Signatu
reID\x3a(?<SignatureID>(.*))$" }
        }
        # remove the original message if parsing was successful
        if !("_grokparsefailure" in [tags]) {
            mutate {
                remove_field => [ "message" ]
           }
        }
      #add_field => [ "received_at", "%{@timestamp}" ]
      #add_field => [ "received_from", "%{host}" ]

    syslog_pri { }
    date {
      match => [ "TimestampAlert", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

Also into the file cyphon filter:

filter {

    # add a universally unique identifier to use for the Elasticsearch
    # document_id so we can retrieve the event from Elasticsearch
    uuid {
        target => "@uuid"
    }

    if [type] != "alert" {
        if [somefield] {
            mutate {
                add_field => {
                    "collection" => "elasticsearch.%{[somefield]}.%{type}"
                }
            }

        } else {
            mutate {
                add_field => {
                    "collection" => "elasticsearch.cyphon.%{type}"
                }
            }
        }
    }
}


Also in the output file is:

output {
    elasticsearch {
        hosts => ["IP_Cyphon:9200"]
        index => "cyphon-%{+YYYY-MM-dd}"
        document_id => "%{@uuid}"
    }

  elasticsearch {
      hosts => ["IP_Cyphon:9200"]
      index => "alert-%{+YYYY.MM.dd}"
      document_type => "system_logs"
  }
###########
    # SEND TO CYPHON #
    ##################
    #
    # replace RabbitMQ 'user' and 'password' values as appropriate
    #
    # send a subset of events to Cyphon Watchdogs
    if [type] in ["intel","siem", "snort"] {
        rabbitmq {
            host => "IP_Cyphon"
            port => 5672
            exchange => "cyphon"
            exchange_type => "direct"
            key => "watchdogs"
            user => "guest"
            password => "guest"
            vhost => "cyphon"
            durable => true
            persistent => true
        }
    }
  stdout { codec => rubydebug }
}


I don't see anything bad...could you check it, please? I follow these tutorial, ...I show perfectly on Kibana all alerts. 


Thanks
