### ISSUE TITLE
Installation script missing escape characters

### ISSUE THREAD

**Issue by callahan22** [controlscanmdr/cyphondock#82]
Very minor.
`echo "sudo docker exec -it cyphondock_cyphon_1 sh -c "python manage.py createsuperuser""`

As the quotes around python and createsuperuser aren't escaped, when copying and pasting from the terminal, the Python script won't complete.
Should be:
`echo "sudo docker exec -it cyphondock_cyphon_1 sh -c \"python manage.py createsuperuser\""`

**Comment by fatalglitch** [comment]
This will be reviewed as part of the Dunbar to ControlScan migration work. Thank you for the report!

**Comment by fatalglitch** [comment]
I just copied and pasted the sudo command, and it ran without issue. Can you provide more information on what wasn't working for you?
