### ISSUE TITLE
Dunbar docker container returning 404

### ISSUE THREAD

**Issue by dbarros** [controlscanmdr/cyphondock#85]
I'm trying to install Cyphon using the Ubuntu ISO (as downloaded from the Cyphon website). When I enter `sudo systemctl status cyphon` I see the following error:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1286/66987121-dca13f00-f10b-11e9-8a2c-9d25e8ab02b2.png">

When I visit the following docker site it returns a 404: https://hub.docker.com/r/dunbar/cyphon/

Is this simply that the Docker container has been removed, or is this some other issue?

**Comment by fatalglitch** [comment]
The prebuilt container has been removed, as we have been transitioning the Cyphon rights to ControlScan from Dunbar. We will be updating the docker-compose and ISO files over the coming weeks for these changes

**Comment by fatalglitch** [comment]
refactor has been performed, please re-pull and try running again
