### ISSUE TITLE
Several Problems on Startup Cyphon

### ISSUE THREAD

**Issue by alexandrecaio** [controlscanmdr/cyphondock#87]
I'm new in Cyphon, so, I just download the Cyphondock from git, because this have all requeriments in one docker-compose configuration. When I try to install my dockers containers with "docker-compose up". Receive a message like:

"for cyphon Container "8081089021" is unhealthy.
Error: Encountered erros while bringing up the project.

**Comment by fatalglitch** [comment]
refactor has been performed, please re-pull and try running again

**Comment by alexandrecaio** [comment]
I have updated my version, other problem appear:

Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 192 MiB in 53 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.3-11-g33bd61f256 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.3-13-g8068beb776 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10338 distinct packages available
OK: 192 MiB in 53 packages
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
(1/1) Installing openssl (1.1.1d-r0)
Executing busybox-1.30.1-r2.trigger
OK: 193 MiB in 54 packages
Connecting to github.com (140.82.114.4:443)
ssl_client: github.com: certificate verification failed: self signed certificate in certificate chain
wget: error getting response: Connection reset by peer
ERROR: Service 'geoip' failed to build: The command '/bin/sh -c BUILD_DEPS='gcc make libc-dev libtool automake autoconf git'  && apk --no-cache add curl-dev ${BUILD_DEPS}  && apk update  && apk add ca-certificates  && update-ca-certificates  && apk add openssl  && wget -O /tmp/geoipupdate.tgz https://github.com/maxmind/geoipupdate/releases/download/v${GEOIPUPDATE_VER}/geoipupdate_${GEOIPUPDATE_VER}_linux_amd64.tar.gz  && tar -zxpvf /tmp/geoipupdate.tgz -C /opt/  && cp /opt/geoipupdate_${GEOIPUPDATE_VER}_linux_amd64/geoipupdate /usr/bin/geoipupdate  && apk del --purge ${BUILD_DEPS}  && rm -rf /var/cache/apk/*  && rm -rf /tmp/geoipupdate.tgz  && rm -rf /opt/geoipupdate_${GEOIPUPDATE_VER}_linux_amd64' returned a non-zero code: 1
[root@docker cyphondock]# (1/1) Installing openssl (1.1.1d-r0)
-bash: erro de sintaxe próximo do `token' não esperado `Installing'
[root@docker cyphondock]# Executing busybox-1.30.1-r2.trigger
-bash: Executing: comando não encontrado
[root@docker cyphondock]# OK: 193 MiB in 54 packages
-bash: OK:: comando não encontrado
[root@docker cyphondock]# Connecting to github.com (140.82.114.4:443)
-bash: erro de sintaxe próximo do `token' não esperado `('
[root@docker cyphondock]# ssl_client: github.com: certificate verification failed: self signed certificate in certificate chain
-bash: ssl_client:: comando não encontrado
[root@docker cyphondock]# wget: error getting response: Connection reset by peer
-bash: wget:: comando não encontrado
[root@docker cyphondock]# ERROR: Service 'geoip' failed to build: The command '/bin/sh -c BUILD_DEPS='gcc make libc-dev libtool automake autoconf git'  && apk --no-cache add curl-dev ${BUILD_DEPS}  && apk update  && apk add ca-certificates  && update-ca-certificates  && apk add openssl  && wget -O /tmp/geoipupdate.tgz https://github.com/maxmind/geoipupdate/releases/download/v${GEOIPUPDATE_VER}/geoipupdate_${GEOIPUPDATE_VER}_linux_amd64.tar.gz  && tar -zxpvf /tmp/geoipupdate.tgz -C /opt/  && cp /opt/geoipupdate_${GEOIPUPDATE_VER}_linux_amd64/geoipupdate /usr/bin/geoipupdate  && apk del --purge ${BUILD_DEPS}  && rm -rf /var/cache/apk/*  && rm -rf /tmp/geoipupdate.tgz  && rm -rf /opt/geoipupdate_${GEOIPUPDATE_VER}_linux_amd64' returned a non-zero code: 1

**Comment by jeylightyear** [comment]
I am also getting error

Service 'geoip' failed to build: Got HTTP status code >= 400: 404 Not Found
