### ISSUE TITLE
OCI runtime create failed

### ISSUE THREAD

**Issue by jadbaz** [controlscanmdr/cyphondock#89]
Environment:
- cyphondock: [latest](https://github.com/controlscanmdr/cyphondock/commit/60d24270e1f3ee01298ab62295778d1021d79833)
- OS: Centos 7.7
- docker: 19.03.4, build 9013bf583a
- docker-compose: 1.24.1, build 4667896b

This is what I get after running `docker-compose up`:

```
ERROR: for watchdogs  Cannot start service watchdogs: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"../entrypoints/run_receiver.sh\": stat ../entrypoints/run_receiver.sh: no such file or directory": unknown

ERROR: for celeryworker  Cannot start service celeryworker: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"../entrypoints/run_celeryworker.sh\": stat ../entrypoints/run_celeryworker.sh: no such file or directory": unknown

ERROR: for celerybeat  Cannot start service celerybeat: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"../entrypoints/run_celerybeat.sh\": stat ../entrypoints/run_celerybeat.sh: no such file or directory": unknown

ERROR: for logchutes  Cannot start service logchutes: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"../entrypoints/run_receiver.sh\": stat ../entrypoints/run_receiver.sh: no such file or directory": unknown
ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
```

**Comment by hbeatty** [comment]
@jadbaz @rfai I ran into the same thing. What it turned out to be for me was not having the cyphon repository.

```
[hbeatty@cyphon1 cyphondock]$ ls ../
cyphon  cyphondock  data
^^^^^^
```
If that directory is already there, remove it and then `git clone https://github.com/controlscanmdr/cyphon.git`. Note that cyphon and cyphondock need to be at the same level in the directory structure.

**Comment by jadbaz** [comment]
Thank you

Now I have another issue
After I run docker-compose up and everything starts, I get the following:
![image](https://user-images.githubusercontent.com/11090042/69245254-2c61a300-0baf-11ea-8f4d-dcf7f909e0fd.png)
This keeps happening and does not stop

Moreover, when I issue `curl localhost:80`, I get 502 bad gateway

**Comment by hbeatty** [comment]
That looks like some type of docker networking issue and is probably not related to Cyphon. I did not run into this.

**Comment by jadbaz** [comment]
You're right, but I'm also tried out [docker-elk](https://github.com/deviantony/docker-elk) on the same machine without any issue.
I'm running all of this inside a VirtualBox VM with NAT networking and port forwarding, do you think this has something to do with it?

**Comment by hbeatty** [comment]
Maybe. I haven't tried it in VirtualBox. I'm doing my testing on a CentOS 7 bare metal machine and then running inside an lxc container.

**Comment by hbeatty** [comment]
In VirtualBox, have you tried setting the "Promiscuous Mode" to "Allow All?" From the Menu Bar it is under Machine -> Settings -> Network -> Advanced.

**Comment by fatalglitch** [comment]
The root of this issue is because we've been refactoring and working only in Dev. I'll be pushing an update soon to fix the volume mapping that is causing this issue.

**Comment by jadbaz** [comment]
Thank you @fatalglitch, the latest commit seems to have fixed the problem

**Comment by jadbaz** [comment]
This did not actually fix the issue
It turns out this is related to #70: when I removed the mapping altogether, the issue stopped happening
