### ISSUE TITLE
Error to setup the Cyphon

### ISSUE THREAD

**Issue by alexandrecaio** [controlscanmdr/cyphondock#90]
Hello! I'm tried to install the Cyphon from Cyphondock base, but i received a error message (My issue was been closed and the problem unsolved).

https://github.com/controlscanmdr/cyphondock/issues/87
The error is in certification?

**Comment by alexandrecaio** [comment]
Command used:
![CMD](https://user-images.githubusercontent.com/20290444/68588747-06c6f200-0469-11ea-90c0-5bf53bc36b2f.png)

Error that appear:
![CMDError](https://user-images.githubusercontent.com/20290444/68588769-10e8f080-0469-11ea-9185-08c052cf44f3.png)

**Comment by alexandrecaio** [comment]
Hi @hbeatty, please give more informations:
Where and How i change this iptable rules on oficial ISO

And this parameters "docker0" and "172.17.0.0/16" are the same for all?

Thanks for share you information

**Comment by hbeatty** [comment]
On CentOS 7 the iptables rules are stored in `/etc/sysconfig/iptables`. These parameters are added to the host machine that is running docker, not the docker containers.

I don't know the answer to your second question because I don't know how the official ISO is configured.

**Comment by fatalglitch** [comment]
If setup correctly, and using the ISO, this should not be needed. Please make sure you are following the setup instructions on ReadTheDocs. These containers 100% need internet access to perform installation and updates

**Comment by alexandrecaio** [comment]
Why are @fatalglitch clossing my issues without a solution? ¬¬'

**Comment by alexandrecaio** [comment]
![aa](https://user-images.githubusercontent.com/20290444/69543078-95f4ff00-0f6b-11ea-80d7-03fbfbb5d61d.png)
My connection on VM is working, an example is I can running normally the image "hello world".
