### ISSUE TITLE
ERROR: unsatisfiable constraints:   py-gdal (missing):     required by: world[py-gdal]

### ISSUE THREAD

**Issue by amitbatajoo** [controlscanmdr/cyphondock#91]
cyphon@cyphon:/opt/cyphon/cyphondock$ sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

fetch http://dl-5.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-5.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-5.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
**ERROR: unsatisfiable constraints:
  py-gdal (missing):
    required by: world[py-gdal]
ERROR: Service 'cyphon' failed to build: The command '/bin/sh -c** apk add -U --no-cache       --repository http://dl-5.alpinelinux.org/alpine/edge/main/       --repository http://dl-5.alpinelinux.org/alpine/edge/testing/       --repository http://dl-5.alpinelinux.org/alpine/edge/community/       binutils       gdal       postgis       proj-dev       py-gdal       su-exec && ln -s /usr/lib/libgdal.so.20 /usr/lib/libgdal.so && ln -s /usr/lib/libgeos_c.so.1 /usr/lib/libgeos_c.so && apk add -U --no-cache       --repository http://dl-5.alpinelinux.org/alpine/edge/main/       --repository http://dl-5.alpinelinux.org/alpine/edge/testing/       --repository http://dl-5.alpinelinux.org/alpine/edge/community/       -t build-deps       build-base       libffi-dev       libressl-dev       openssl-dev       linux-headers       musl-dev       postgis       postgresql-dev       python3-dev       jpeg-dev       zlib-dev       tiff-dev && pip install --upgrade pip && pip install -r $CYPHON_HOME/requirements.txt && apk del build-deps && python -m nltk.downloader -d /usr/local/share/nltk_data punkt wordnet' returned a non-zero code: 1
-----------------------------------------------------------------------------------------------
Please help me how to overcome with this problem.

Thank you in advance.

**Comment by adonix-dev** [comment]
UP !
